import Layout from "../components/Layout";
import Link from "next/link";

export default function AboutPage() {
  return (
    <Layout
      title="About Chris Izworski: Perfect Lawn Advisor"
      description="Chris Izworski is a Bay City, Michigan gardener, outdoorsman, and writer who built Perfect Lawn Advisor to bring hyperlocal turfgrass science to Michigan homeowners."
      canonical="https://lawn.chrisizworski.com/about"
    >
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{
          __html: JSON.stringify({
            "@context": "https://schema.org",
            "@type": "Person",
            name: "Chris Izworski",
            url: "https://chrisizworski.com",
            sameAs: ["https://chrisizworski.com", "https://freighterviewfarms.com", "https://trout.chrisizworski.com"],
            jobTitle: "Gardening Writer, Outdoorsman, Lawn Care Researcher",
            address: { "@type": "PostalAddress", addressLocality: "Bay City", addressRegion: "Michigan" },
            knowsAbout: ["Lawn Care", "Turfgrass Science", "Michigan Gardening", "USDA Hardiness Zones", "Cool-Season Grasses"],
          }),
        }}
      />

      <div className="hero-dark" style={{ padding: "56px 24px" }}>
        <div className="container-narrow">
          <div className="breadcrumb" style={{ color: "rgba(197,232,160,0.6)" }}>
            <Link href="/" style={{ color: "var(--green-bright)" }}>Perfect Lawn Advisor</Link>
            <span className="breadcrumb-sep">›</span>
            <span>About</span>
          </div>
          <h1 style={{ fontFamily: "var(--font-display)", fontSize: "clamp(28px,5vw,48px)", fontWeight: 900, color: "var(--green-pale)", margin: "16px 0 12px" }}>
            About Chris Izworski &amp; Perfect Lawn Advisor
          </h1>
          <p style={{ color: "var(--green-light)", fontSize: 16, lineHeight: 1.7, opacity: 0.9, maxWidth: 560 }}>
            Hyperlocal lawn care for Michigan homeowners who are tired of generic advice that ignores their zone, their soil, and their season.
          </p>
        </div>
      </div>

      <div className="container-narrow" style={{ padding: "56px 24px" }}>
        <div className="prose">
          <h2>Why I Built This</h2>
          <p>
            I'm <a href="https://chrisizworski.com">Chris Izworski</a>, a Bay City, Michigan outdoorsman, 
            gardener, and writer. My wife and I run <a href="https://freighterviewfarms.com">Freighter View Farms</a>, 
            a Great Lakes-inspired gardening and seed-saving blog rooted in Zone 6a growing conditions.
          </p>
          <p>
            After years of watching Michigan homeowners follow national lawn care schedules designed for 
            generic "Zone 6" conditions, missing their actual frost dates, ignoring their soil type, and buying fertilizer at the wrong time. I decided to build something better.
          </p>
          <p>
            Perfect Lawn Advisor uses AI and real-time weather data to generate personalized lawn care 
            plans based on your exact ZIP code. Not your state. Not your region. Your yard.
          </p>

          <h2>The Michigan Difference</h2>
          <p>
            Michigan spans four USDA hardiness zones and multiple grass-growing climates. A lawn in 
            Marquette (Zone 5a, 120-day season) behaves completely differently than one in Kalamazoo 
            (Zone 6b, 175-day season). Even within the same zone, soil type matters: the heavy clay 
            of Saginaw County and the sandy loam of Leelanau County require different fertilizer 
            timing, irrigation strategies, and aeration schedules.
          </p>
          <p>
            This site acknowledges that complexity and builds it into every recommendation.
          </p>

          <h2>Methodology</h2>
          <p>
            Every personalized plan generated by the ZIP code tool is grounded in:
          </p>
        </div>

        <div className="card" style={{ marginBottom: 32, background: "var(--green-pale)", border: "none" }}>
          {[
            ["USDA Hardiness Zone mapping", "Precise zone assignment by ZIP using USDA Plant Hardiness Zone Map data"],
            ["NRCS Web Soil Survey", "Soil type, drainage class, and organic matter levels by county"],
            ["NOAA Climatology", "Historical frost dates, precipitation averages, and temperature normals"],
            ["NWS Current Conditions", "Live weather data via web search for in-season recommendations"],
            ["MSU Extension Research", "Michigan State University turfgrass management guidelines"],
            ["Amazon Associates vetting", "Product recommendations are real, searchable products, not fabricated names"],
          ].map(([title, desc], i) => (
            <div key={i} style={{ display: "flex", gap: 14, padding: "12px 0", borderBottom: i < 5 ? "1px solid var(--border)" : "none", alignItems: "flex-start" }}>
              <span style={{ color: "var(--green-bright)", fontWeight: 900, marginTop: 2 }}>✓</span>
              <div>
                <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 14, color: "var(--green-dark)" }}>{title}</div>
                <div style={{ fontSize: 13, color: "var(--text-muted)" }}>{desc}</div>
              </div>
            </div>
          ))}
        </div>

        <div className="prose">
          <h2>More From Chris Izworski</h2>
          <p>
            This site is part of a broader network of Michigan-focused outdoor content I maintain:
          </p>
        </div>

        <div style={{ display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))", gap: 16, margin: "24px 0 48px" }}>
          {[
            { href: "https://chrisizworski.com", title: "chrisizworski.com", desc: "Personal hub: 911 tech, outdoors, gardening, Michigan" },
            { href: "https://freighterviewfarms.com", title: "Freighter View Farms", desc: "Great Lakes gardening, seed saving, zone 6a growing" },
            { href: "https://trout.chrisizworski.com", title: "Michigan Trout Report", desc: "River conditions, hatches, and trout fishing across Michigan" },
          ].map((site, i) => (
            <a key={i} href={site.href} target="_blank" rel="noopener noreferrer" className="city-card" style={{ display: "block" }}>
              <div style={{ fontFamily: "var(--font-display)", fontWeight: 700, fontSize: 14, color: "var(--green-dark)", marginBottom: 6 }}>{site.title}</div>
              <div style={{ fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 }}>{site.desc}</div>
            </a>
          ))}
        </div>

        <div style={{ textAlign: "center", marginTop: 16 }}>
          <Link href="/" className="btn btn-primary">Get My Lawn Plan →</Link>
        </div>
      </div>
    </Layout>
  );
}
